
- hosts: local.centos
  
  tasks:
  
  - name: Facts...
    ec2_remote_facts:
      filters:
        instance-state-name: running
        "tag:Name": terraria
      region: us-east-1
      aws_access_key: '{{ lookup("env","AWS_ACCESS_KEY") }}'
      aws_secret_key: '{{ lookup("env","AWS_SECRET_KEY") }}'
    register: ec2
  
  - set_fact:
      target_ids: '{{ ec2["instances"] | map(attribute="id") | list }}'
  
  - debug:
      var: target_ids
  
  - name: Stop terraria instances
    ec2:
      instance_ids: '{{ target_ids }}'
      state: stopped
      region: us-east-1
      aws_access_key: '{{ lookup("env","AWS_ACCESS_KEY") }}'
      aws_secret_key: '{{ lookup("env","AWS_SECRET_KEY") }}'
    
